Lab 2
Anny-waay/IS-2022-Web-CupCake pull request #4
Opened 2022-10-09 18:53 UTC by Anny-waay

2022-10-17 11:53 UTC, BakasaRus requested changes
Закинуть куда-нибудь `line-height`, `text-indent`, `font-style`

2022-10-17 11:53 UTC, BakasaRus commented on css/site.css
> +    vertical-align: top;
Обычно с блоками такой трюк не прокатывает, а у тебя сработал. Что за магия?

2022-10-21 08:11 UTC, Anny-waay commented on css/site.css
> +    vertical-align: top;
Из-за того, что это строчный блок (display: inline-block;)

2022-10-31 11:55 UTC, BakasaRus approved these changes

2022-10-31 12:52 UTC, merged