Lab 3
Anny-waay/IS-2022-Web-CupCake pull request #5
Opened 2022-10-16 22:31 UTC by Anny-waay

2022-10-17 12:04 UTC, BakasaRus requested changes
1. На маленьких экранах лучше делать один столбец с товарами вместо двух и один столбец с категориями (а картинку в начале луче скрыть, всё равно нечитаемая)
2. Лого в шапке на маленьких экранах едет :(
3. Табличку лучше попробовать сверстать на гридах
4.

2022-10-17 12:04 UTC, BakasaRus commented on css/site.css
> +    z-index: 9998!important;
А что это такое?

2022-10-21 08:40 UTC, Anny-waay commented on css/site.css
> +    z-index: 9998!important;
z-index определяет положение позиционированного элемента и его дочерних элементов или флекс-элементов по оси z. Здесь z-index: 9998!important, чтобы шапка перекрывала все остальное при пролистывании страницы

2022-10-31 11:55 UTC, BakasaRus approved these changes

2022-10-31 12:52 UTC, merged