Lab 4
Anny-waay/IS-2022-Web-CupCake pull request #6
Opened 2022-11-14 11:03 UTC by Anny-waay

2022-11-14 11:31 UTC, BakasaRus requested changes

2022-11-14 11:31 UTC, BakasaRus commented on scripts/display_location.js
> +catch (e) {}
1. Ссылки можно перебирать в цикле и сравнивать с текущей, это позволит не писать два раза одно и то же
2. [Code Style](https://github.com/airbnb/javascript)

2022-11-14 11:31 UTC, BakasaRus commented on scripts/page_load_time.js
> +})();
Что за конструкция из скобок?

2022-11-27 16:34 UTC, Anny-waay commented on scripts/page_load_time.js
> +})();
Конструкция, чтобы функция выполнялась сразу же после того, как она была определена

2022-12-12 10:17 UTC, merged